import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import styled from 'styled-components';

/**
 * スタイル付きコンポーネント定義
 * アプリケーションのUIレイアウトとスタイルを設定
 */
const Container = styled.div`
  display: flex;
  height: 100vh;
  background-color: white;
`;
const ContentArea = styled.div`
  width: 80%;
  padding: 30px 20px 0 60px;
  display: flex;
  flex-direction: column;
  height: 100%;
`;

const ItemArea = styled.div`
  display: flex;
  width: 500px;
  height: 40px;
  justify-content: space-between;
  align-items: center;
  margin-top: 30px;
  margin-bottom: 30px;
`;

const CsvArea = styled.div`
  display: flex;
  width: 500px;
  justify-content: space-between;
  align-items: left;
  margin-top: 50px;
  height: 200px;
  flex-direction: column;
`;

const LabelArea = styled.div`
  font-family: Noto Sans JP;
  font-size: 16px;
  font-weight: 700;
  line-height: 23px;
  letter-spacing: 0em;
  text-align: left;
  color: #000000;
`;

const SelectArea = styled.select.attrs({ required: true })`
  box-shadow: 0px 0px 10px 0px #0000001a;
  border: none;
  width: 330px;
  height: 46px;
  border-radius: 8px;
  padding: 12px;
  font-size: 16px;
`;

const ScrollableTableContainer = styled.div`
  overflow: auto;
  flex-grow: 1;
  margin-bottom: 40px;
`;

const Form = styled.form``;

const FileInputContainer = styled.div`
  border: 2px dashed #b2b2b2;
  padding: 20px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  width: 500px;
  height: 200px;
  justify-content: center;
  cursor: pointer;
  background-color: #e9ecef;
  &:hover {
    opacity: 0.5;
  }
`;

const FileInputLabel = styled.label`
  color: #b2b2b2;
  font-weight: bold;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
`;

const FileInput = styled.input`
  display: none;
`;

const SubmitButton = styled.button`
  width: 500px;
  height: 60px;
  padding: 10px;
  margin: 20px 0;
  background: #ff9900;
  color: white;
  border: none;
  border-radius: 10px;
  cursor: pointer;
  font-family: Noto Sans JP;
  font-size: 16px;
  font-weight: 700;
  line-height: 24px;
  letter-spacing: 0em;

  &:hover {
    opacity: 0.8;
  }
`;

const CheckBoxDescription = styled.div`
  font-size: 16px;
  font-weight: 400;
  line-height: 23.17px;
  text-align: left;
  color: #070002e5;
`;
const CheckBoxGroup = styled.div`
  flex-direction: column;
  gap: 16px;
  margin-top: 30px;
`;

const CsvFormatText = styled.p`
  font-size: 16px;
  margin: 10px 0;
`;

/**
 * メインページコンポーネント
 * 以下の機能を提供します：
 * 1. メールテンプレートの選択
 * 2. CSVファイルのアップロード（ドラッグ＆ドロップ対応）
 * 3. 領収書メール送信のための確認チェック
 * 4. サーバーへのCSVファイル送信
 */
export default function Home() {
  // ルーターとステート管理
  const router = useRouter();
  const [selectedTemplate, setSelectedTemplate] = useState('');
  const [isLoading, setLoading] = useState(false);
  const [fileName, setFileName] = useState<string | null>(null);
  const [csvFile, setCsvFile] = useState<File | null>(null);
  const [isAgreeReceiptMail, setIsAgreeReceiptMail] = useState(false);

  /**
   * メールテンプレート選択時の処理
   * テンプレートが変更されると、関連する状態をリセットします
   */
  const handleSelectChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const value = event.target.value;
    setSelectedTemplate(value);
    setIsAgreeReceiptMail(false);
    setFileName(null);
    setCsvFile(null);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol>
            <li>
              Get started by editing <code>src/pages/index.tsx</code>.
            </li>
            <li>Save and see your changes instantly.</li>
          </ol>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Deploy now
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Read our docs
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
      </div>
    </>
  );
}
